# Generated by Django 3.2.7 on 2021-09-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blognote',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterField(
            model_name='blognote',
            name='img',
            field=models.ImageField(blank=True, upload_to='resources/images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
