# Generated by Django 3.2.7 on 2021-09-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blognote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognote',
            name='txt',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
