# Generated by Django 3.2.8 on 2021-10-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blognote_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognote',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=None, null=True, unique=True, verbose_name='URL'),
        ),
    ]
