# Generated by Django 3.2.8 on 2021-10-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blognote_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognote',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True, verbose_name='URL'),
        ),
    ]
