# Generated by Django 3.2.8 on 2021-10-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blognote_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognote',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Название'),
        ),
    ]
