# Generated by Django 3.2.8 on 2021-10-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211020_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognote',
            name='title',
            field=models.CharField(max_length=80, unique=True, verbose_name='Название'),
        ),
    ]
