# Generated by Django 3.2.9 on 2021-11-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognote',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
