# Generated by Django 3.2.9 on 2021-11-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blognote_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognote',
            name='slug',
        ),
    ]
